#!/usr/bin/env bash
# Install Nginx and the init file have only a message
sudo apt update -y
sudo apt upgrade -y
sudo apt install nginx -y
sudo service nginx start
ufw allow "Nginx HTTP"
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service restart
